jwt:
  secret: dfslauisdfjadsbyuwebhf
  sessionTime: 860000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heartstone?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234

